
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 42;
  public static final int FUNCTION = 14;
  public static final int WITH = 37;
  public static final int CONST = 6;
  public static final int PACKED = 24;
  public static final int GE = 48;
  public static final int CASE = 5;
  public static final int REPEAT = 28;
  public static final int ARRAY = 3;
  public static final int MINUS = 40;
  public static final int FOR = 13;
  public static final int WRITE = 61;
  public static final int STRINGCONST = 68;
  public static final int SEMICOLON = 53;
  public static final int NOT = 21;
  public static final int AND = 2;
  public static final int LT = 45;
  public static final int RIGHTSQ = 57;
  public static final int RECORD = 27;
  public static final int INTCONST = 65;
  public static final int TYPE = 32;
  public static final int NIL = 20;
  public static final int IN = 17;
  public static final int OR = 23;
  public static final int COMMA = 52;
  public static final int DOTDOT = 55;
  public static final int DIV = 7;
  public static final int BEGIN = 4;
  public static final int UNTIL = 34;
  public static final int LEFTSQ = 56;
  public static final int PLUS = 39;
  public static final int WRITELN = 62;
  public static final int ASSIGN = 38;
  public static final int IF = 16;
  public static final int PTR = 58;
  public static final int DOT = 49;
  public static final int LE = 47;
  public static final int LEFT = 50;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 26;
  public static final int MOD = 19;
  public static final int IDENT = 63;
  public static final int READLN = 59;
  public static final int EQ = 43;
  public static final int TIMES = 41;
  public static final int COLON = 54;
  public static final int ELSE = 10;
  public static final int READ = 60;
  public static final int TO = 31;
  public static final int FILE = 12;
  public static final int GOTO = 15;
  public static final int CHARCONST = 67;
  public static final int WHILE = 36;
  public static final int REALCONST = 66;
  public static final int THEN = 30;
  public static final int BOOLCONST = 64;
  public static final int NE = 44;
  public static final int END = 11;
  public static final int DOWNTO = 9;
  public static final int USES = 33;
  public static final int RIGHT = 51;
  public static final int LABEL = 18;
  public static final int GT = 46;
  public static final int VAR = 35;
  public static final int PROCEDURE = 25;
  public static final int DO = 8;
  public static final int SET = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "ARRAY",
  "BEGIN",
  "CASE",
  "CONST",
  "DIV",
  "DO",
  "DOWNTO",
  "ELSE",
  "END",
  "FILE",
  "FOR",
  "FUNCTION",
  "GOTO",
  "IF",
  "IN",
  "LABEL",
  "MOD",
  "NIL",
  "NOT",
  "OF",
  "OR",
  "PACKED",
  "PROCEDURE",
  "PROGRAM",
  "RECORD",
  "REPEAT",
  "SET",
  "THEN",
  "TO",
  "TYPE",
  "USES",
  "UNTIL",
  "VAR",
  "WHILE",
  "WITH",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "DOT",
  "LEFT",
  "RIGHT",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "DOTDOT",
  "LEFTSQ",
  "RIGHTSQ",
  "PTR",
  "READLN",
  "READ",
  "WRITE",
  "WRITELN",
  "IDENT",
  "BOOLCONST",
  "INTCONST",
  "REALCONST",
  "CHARCONST",
  "STRINGCONST"
  };
}

